'use strict';
const PLANTS=[
{id:'strawberry',name:'イチゴ',family:'バラ科',season:'春',fact:'葉はふつう3枚の小さな葉に分かれ、白い花を咲かせます。',detail:'赤い部分は、花の土台がふくらんだもの。表面のつぶつぶが、植物学でいう一つひとつの果実です。',q:'イチゴの赤い表面にある、つぶつぶは何？',choices:['一つひとつの果実','花びら','小さな葉'],answer:0},
{id:'sunflower',name:'ヒマワリ',family:'キク科',season:'夏',fact:'大きな花に見える部分には、たくさんの小さな花が集まっています。',detail:'外側の黄色い花と、中心に集まる小さな花でできています。中心の花から、やがて種の入った果実ができます。',q:'ヒマワリの大きな花は、どんなつくり？',choices:['1枚の大きな花びら','たくさんの小さな花の集まり','葉だけの集まり'],answer:1},
{id:'hydrangea',name:'アジサイ',family:'アジサイ科',season:'初夏',fact:'花びらのように目立つ部分は、おもに「がく」です。',detail:'がくは花の一部です。アジサイの仲間には、目立つ装飾花と、小さな両性花をつけるものがあります。品種によって形が違います。',q:'アジサイの花びらのように目立つ部分は、おもに何？',choices:['根','がく','種'],answer:1},
{id:'tulip',name:'チューリップ',family:'ユリ科',season:'春',fact:'地下の球根に、育つための養分をたくわえます。',detail:'球根は、厚くなった葉などが集まったものです。花が終わったあとも、葉は光を受けて養分をつくります。',q:'チューリップが養分をたくわえるものは？',choices:['花びらだけ','地下の球根','空中のつる'],answer:1},
{id:'mint',name:'ミント',family:'シソ科',season:'夏〜秋',fact:'葉に香りがあり、向かい合って葉がつくものが多いハーブです。',detail:'ミントにはスペアミントやペパーミントなど、多くの種類があります。地下茎で広がるため、鉢で育てる方法もあります。',q:'ミントでよく知られている特徴は？',choices:['葉に香りがある','海の中で育つ','葉がまったくない'],answer:0},
{id:'morningglory',name:'アサガオ',family:'ヒルガオ科',season:'夏',fact:'つるが伸び、じょうごのような形の花が咲きます。',detail:'支柱などに、つるを巻きつけて育ちます。日本で親しまれるアサガオは、朝に花が開くことが多い植物です。',q:'アサガオは、どうやって支柱を登る？',choices:['根で空を飛ぶ','つるを巻きつける','花びらでつかむ'],answer:1}
];
const KEY='secret-botanical-garden-v1';
const initial=()=>({version:1,seeds:50,owned:{strawberry:1},observed:[],learned:[],selected:'strawberry',draws:0});
function valid(s){return s&&s.version===1&&Number.isSafeInteger(s.seeds)&&s.seeds>=0&&s.seeds<1e9&&Number.isSafeInteger(s.draws)&&s.draws>=0&&s.owned&&typeof s.owned==='object'&&!Array.isArray(s.owned)&&Object.entries(s.owned).every(([k,v])=>PLANTS.some(p=>p.id===k)&&Number.isSafeInteger(v)&&v>0&&v<1e6)&&Object.keys(s.owned).length>0&&['observed','learned'].every(k=>Array.isArray(s[k])&&s[k].every(id=>PLANTS.some(p=>p.id===id)))&&PLANTS.some(p=>p.id===s.selected)&&s.owned[s.selected];}
let state=initial(), storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(valid(parsed))state=parsed;else storageOK=false;}}catch{storageOK=false;}
let welcomeGiftReceived=false;
let tab='garden',quizIndex=0,answered=false,toastTimer;
const main=document.getElementById('main'),modal=document.getElementById('modal');
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;storageOK=true;document.getElementById('save').textContent='保存済み';return true;}catch{storageOK=false;document.getElementById('save').textContent='保存できません';toast('保存できません。バックアップで進み具合を残せます。');return false;}}
function transact(fn){const next=structuredClone(state);fn(next);return persist(next);}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function art(p){const i=PLANTS.indexOf(p);return `<div class="plant-art" role="img" aria-label="${p.name}のイラスト" style="background-position:${i%3*50}% ${Math.floor(i/3)*100}%"></div>`;}
function cards(ownedOnly=false){return PLANTS.filter(p=>!ownedOnly||state.owned[p.id]).map(p=>`<button class="plant-card ${state.owned[p.id]?'':'locked'}" data-plant="${p.id}">${art(p)}<span class="badge">${state.owned[p.id]?'育成中':'未発見'}</span><strong>${p.name}</strong><small>${p.family} · ${p.season}</small></button>`).join('');}
function ambient(){return '<div class="garden-light" aria-hidden="true">'+Array.from({length:10},(_,i)=>`<i style="--x:${8+(i*29)%85}%;--y:${20+(i*17)%65}%;--delay:${-i*1.7}s;--duration:${7+i%4}s"></i>`).join('')+'</div>';}
function celebrate(kind='seeds'){
 if(window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;
 const host=modal.open?document.getElementById('modal-content'):document.querySelector('.app');
 const fx=document.createElement('div');fx.className='celebration '+kind;fx.setAttribute('aria-hidden','true');
 for(let i=0;i<22;i++){const star=document.createElement('span');star.textContent=kind==='bloom'?(i%3?'✦':'❀'):(i%3?'✧':'❧');star.style.setProperty('--dx',Math.round((Math.random()-.5)*300)+'px');star.style.setProperty('--dy',Math.round(-60-Math.random()*240)+'px');star.style.setProperty('--spin',Math.round((Math.random()-.5)*180)+'deg');star.style.setProperty('--delay',i*13+'ms');fx.append(star);}
 host.append(fx);setTimeout(()=>fx.remove(),1800);
 const wallet=document.querySelector('.wallet');wallet.classList.remove('reward-pop');void wallet.offsetWidth;wallet.classList.add('reward-pop');
}
function render(){document.body.dataset.view=tab;document.getElementById('seeds').textContent=state.seeds;document.getElementById('save').textContent=storageOK?'保存済み':'保存できません';document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});
if(tab==='garden'){const p=PLANTS.find(p=>p.id===state.selected);main.innerHTML=`<section class="scene" aria-label="陽が差すひみつの温室"><img src="assets/garden.png" alt="植物が茂る美しい温室"/>${ambient()}<span class="scene-label">☀ ひみつの温室</span><span class="scene-note">${Object.keys(state.owned).length}種類の植物が仲間入り</span></section><div class="content garden-content"><div class="play-guide"><strong>🌱 目標は、6種類の植物を集めること！</strong><span>観察かクイズで種をもらう → ガチャを引く</span><button class="secondary" id="howto">遊び方を見る</button><button class="primary" id="quiz-shortcut">クイズで種を集める</button></div><section class="today">${art(p)}<div><span class="kicker">今日の観察</span><h2>${p.name}</h2><p>${p.fact}</p><button class="primary" data-observe="${p.id}">観察する</button></div></section><div><button class="gacha" id="draw"><span class="seed-icon">🌰</span><span><strong>たねガチャ</strong><small>${state.seeds<20?`あと${20-state.seeds}個で引けます`:'集めた種で、植物と出会おう'}</small></span><span>たね × 20</span></button><div class="gacha-actions"><button class="primary" id="draw-ten" ${state.seeds<200?'disabled':''}>✨ 10連ガチャ · たね200個</button><button class="secondary" id="daily-gift" ${state.lastGift===todayKey()?'disabled':''}>${state.lastGift===todayKey()?'今日のプレゼントは受け取り済み':'🎁 今日のたねをもらう · +200'}</button></div><p class="muted">1回20個。観察で20個、クイズは初回30個・復習20個。かぶった植物は種10個に変わります。</p></div><details class="collection"><summary class="section-title"><span>わたしの植物園</span><span class="count">${Object.keys(state.owned).length} / 6 種類 · 開く</span></summary><div class="grid">${cards(true)}</div></details></div>`;}
if(tab==='book')main.innerHTML=`<div class="content"><div class="intro"><span class="kicker">BOTANICAL NOTEBOOK</span><h2>植物の図鑑</h2><p>葉のかたち、花のひみつ。気になる植物を開いてみよう。<br>まだ出会っていない植物も、観察できます。</p><progress max="6" value="${state.observed.length}" aria-label="観察した植物の数"></progress><p class="muted">観察 ${state.observed.length}/6 · クイズ ${state.learned.length}/6</p></div><div class="grid">${cards()}</div><div class="sources"><p>イラストは学習を楽しむための描画です。品種による違いがあります。</p><a href="https://www.shuminoengei.jp/m-pc/a-page_p_top" target="_blank" rel="noopener">もっと調べる：NHK みんなの趣味の園芸 植物図鑑</a></div></div>`;
if(tab==='quiz')renderQuiz();bind();}
function bind(){main.querySelectorAll('[data-plant]').forEach(b=>b.onclick=()=>observe(b.dataset.plant));main.querySelectorAll('[data-observe]').forEach(b=>b.onclick=()=>observe(b.dataset.observe));const draw=document.getElementById('draw');if(draw){draw.disabled=state.seeds<20;draw.onclick=()=>gacha(1);}const ten=document.getElementById('draw-ten');if(ten)ten.onclick=()=>gacha(10);const help=document.getElementById('howto');if(help)help.onclick=()=>showGuide();const shortcut=document.getElementById('quiz-shortcut');if(shortcut)shortcut.onclick=()=>{tab='quiz';render();window.scrollTo({top:0,behavior:'smooth'});};const gift=document.getElementById('daily-gift');if(gift)gift.onclick=()=>{if(state.lastGift===todayKey())return;if(transact(s=>{s.seeds+=200;s.lastGift=todayKey();})){render();toast('今日のプレゼント！ たね +200');celebrate();}};}
function show(html){document.getElementById('modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
function observe(id){const p=PLANTS.find(p=>p.id===id),done=state.observed.includes(id);show(`${art(p)}<span class="kicker">${p.family} · ${p.season}</span><h2>${p.name}</h2><p>${p.fact}</p><p>${p.detail}</p><button class="primary" id="learn" ${done?'disabled':''}>${done?'観察ずみ':'観察を記録する · たね +20'}</button>${state.owned[id]?'<div class="actions"><button class="secondary" id="select">温室に飾る</button></div>':''}<p class="muted">知らない植物を口に入れたり、さわったりしないでね。</p>`);document.getElementById('learn').onclick=()=>{if(state.observed.includes(id))return;if(transact(s=>{s.observed.push(id);s.seeds+=20;})){render();observe(id);toast('観察を記録しました。たね +20');celebrate();}};const select=document.getElementById('select');if(select)select.onclick=()=>{if(transact(s=>s.selected=id)){tab='garden';render();modal.close();toast(`${p.name}を温室に飾りました`);}};}
function pickPlant(){const bytes=new Uint32Array(1);let v;do{crypto.getRandomValues(bytes);v=bytes[0];}while(v>=4294967292);return PLANTS[v%6];}
function gacha(count=1){
 if(![1,10].includes(count)||state.seeds<count*20)return;
 const results=Array.from({length:count},()=>({p:pickPlant(),duplicate:false}));
 if(!transact(s=>{s.seeds-=count*20;s.draws+=count;for(const r of results){r.duplicate=!!s.owned[r.p.id];if(r.duplicate)s.seeds+=10;else{s.owned[r.p.id]=1;s.selected=r.p.id;}}}))return;
 render();
 if(count===1){const {p,duplicate}=results[0];show(`<div class="result"><span class="kicker">${duplicate?'また会えたね':'新しい植物を発見！'}</span>${art(p)}<h2>${p.name}</h2><p>${p.fact}</p><p>${duplicate?'持っている植物なので、たね10個になりました。':'あなたの植物園に仲間入りしました。'}</p><button class="primary" id="result-observe">観察して種をもらう</button><p class="muted">全6種類・それぞれ同じ確率（1/6）</p></div>`);document.getElementById('result-observe').onclick=()=>observe(p.id);
 }else{const fresh=results.filter(r=>!r.duplicate).length;const refund=results.filter(r=>r.duplicate).length*10;show(`<div class="result"><span class="kicker">10連ガチャの結果</span><h2>🌸 ${fresh}種類が仲間入り！</h2><div class="draw-results">${results.map((r,i)=>`<button class="draw-result ${r.duplicate?'':'new-plant'}" data-result="${r.p.id}" style="--reveal-delay:${i*70}ms">${art(r.p)}<strong>${r.p.name}</strong><small>${r.duplicate?'たね +10':'NEW！'}</small></button>`).join('')}</div><p>かぶった植物から、たね${refund}個が戻りました。</p><p class="muted">植物を押すと観察できます。全6種類・各1/6の確率。</p></div>`);document.querySelectorAll('[data-result]').forEach(el=>el.onclick=()=>observe(el.dataset.result));}
 const again=document.createElement('button');again.className='primary draw-again';again.textContent=count===10?'もう一度10連 · 200個':'もう一度引く · 20個';again.disabled=state.seeds<count*20;again.onclick=()=>gacha(count);document.getElementById('modal-content').append(again);celebrate('bloom');
}
function todayKey(){const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;}
function showGuide(welcome=false){show(`<div class="guide-dialog"><span class="kicker">はじめてでも、すぐ遊べる</span><h2>🌱 植物を集めて、庭を育てよう</h2>${welcome?'<p class="gift-message">たね500個をプレゼントしました！<br>まずはガチャを引いてみよう。</p>':''}<ol><li><strong>観察する</strong><p>植物を開き「観察を記録する」を押すと、初回は種20個。図鑑の未発見の植物も観察できます。</p></li><li><strong>クイズで種を集める</strong><p>答えたあと「解説を読んだ」を押すと初回30個、復習は20個。間違えてももらえます。</p></li><li><strong>ガチャで植物を増やす</strong><p>1回20個、10連200個。全6種類を集めよう！同じ植物は種10個になります。</p></li></ol><p>🎁 毎日「今日のたねをもらう」で200個追加！<br>集めた植物は「温室に飾る」で観察カードに選べます。</p><button class="primary" id="start-gacha">さっそくガチャを引く · 20個</button><button class="secondary" id="start-quiz">クイズで種を集める</button></div>`);document.getElementById('start-gacha').onclick=()=>{modal.close();tab='garden';render();if(state.seeds>=20)gacha(1);else toast('クイズか今日のプレゼントで種を集めよう');};document.getElementById('start-quiz').onclick=()=>{modal.close();tab='quiz';render();window.scrollTo({top:0,behavior:'smooth'});};}
function renderQuiz(){const p=PLANTS[quizIndex];main.innerHTML=`<div class="content"><div class="intro"><span class="kicker">小さな発見を、おぼえよう</span><h2>植物のクイズ</h2><p>間違えても大丈夫。解説を読んで学ぼう。</p></div><section class="quiz-panel"><span class="kicker">${quizIndex+1} / 6 · ${p.name}</span>${art(p)}<h3>${p.q}</h3><div class="options">${p.choices.map((c,i)=>`<button data-answer="${i}">${c}</button>`).join('')}</div><div id="feedback" class="feedback" role="status"></div></section></div>`;answered=false;main.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));}
function answer(i){if(answered)return;answered=true;const p=PLANTS[quizIndex];main.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;const v=Number(b.dataset.answer);if(v===p.answer)b.classList.add('correct');else if(v===i)b.classList.add('wrong');});const done=state.learned.includes(p.id);document.getElementById('feedback').innerHTML=`<strong>${i===p.answer?'正解！':'おしい！ 正解は「'+p.choices[p.answer]+'」'}</strong><p>${p.detail}</p><button class="primary" id="claim">${done?'復習を記録する · たね +20':'解説を読んだ · たね +30'}</button>`;document.getElementById('claim').onclick=()=>{const review=state.learned.includes(p.id);if(!transact(s=>{if(!review)s.learned.push(p.id);s.seeds+=review?20:30;}))return;toast(review?'復習しました。たね +20':'学びを記録しました。たね +30');quizIndex=(quizIndex+1)%PLANTS.length;render();celebrate();};}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();window.scrollTo({top:0,behavior:'smooth'});});document.getElementById('close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
document.getElementById('settings').onclick=()=>{show(`<h2>セーブとバックアップ</h2><p>進み具合は、このブラウザに自動保存されます。ガチャの結果は、表示される前に保存します。</p><p class="muted">ブラウザのデータを消すとセーブも消えます。別の端末や公開後のURLへ移すときは、バックアップを使ってください。</p><div class="actions"><button class="primary" id="export">バックアップを保存</button><button class="secondary" id="restore">バックアップを読み込む</button></div>`);document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='secret-garden-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};document.getElementById('restore').onclick=()=>document.getElementById('import').click();};
document.getElementById('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error();const parsed=JSON.parse(await file.text());if(!valid(parsed))throw Error();show(`<h2>バックアップを読み込む？</h2><p>現在の進み具合を、たね${parsed.seeds}個・植物${Object.keys(parsed.owned).length}種類のセーブに置き換えます。</p><button class="primary" id="confirm-import">このセーブを読み込む</button>`);document.getElementById('confirm-import').onclick=()=>{if(persist(parsed)){render();modal.close();toast('バックアップを読み込みました');}};}catch{toast('このファイルは読み込めません。セーブは変更していません。');}e.target.value='';};
if(storageOK&&!state.gachaWelcome){welcomeGiftReceived=transact(s=>{s.seeds+=500;s.gachaWelcome=true;});}
render();if(welcomeGiftReceived)showGuide(true);if(!storageOK)toast('セーブを確認できませんでした。バックアップをご確認ください。');
