'use strict';
const PLANTS=[
{id:'strawberry',name:'イチゴ',family:'バラ科',season:'春',fact:'葉はふつう3枚の小さな葉に分かれ、白い花を咲かせます。',detail:'赤い部分は、花の土台がふくらんだもの。表面のつぶつぶが、植物学でいう一つひとつの果実です。',q:'イチゴの赤い表面にある、つぶつぶは何？',choices:['一つひとつの果実','花びら','小さな葉'],answer:0},
{id:'sunflower',name:'ヒマワリ',family:'キク科',season:'夏',fact:'大きな花に見える部分には、たくさんの小さな花が集まっています。',detail:'外側の黄色い花と、中心に集まる小さな花でできています。中心の花から、やがて種の入った果実ができます。',q:'ヒマワリの大きな花は、どんなつくり？',choices:['1枚の大きな花びら','たくさんの小さな花の集まり','葉だけの集まり'],answer:1},
{id:'hydrangea',name:'アジサイ',family:'アジサイ科',season:'初夏',fact:'花びらのように目立つ部分は、おもに「がく」です。',detail:'がくは花の一部です。アジサイの仲間には、目立つ装飾花と、小さな両性花をつけるものがあります。品種によって形が違います。',q:'アジサイの花びらのように目立つ部分は、おもに何？',choices:['根','がく','種'],answer:1},
{id:'tulip',name:'チューリップ',family:'ユリ科',season:'春',fact:'地下の球根に、育つための養分をたくわえます。',detail:'球根は、厚くなった葉などが集まったものです。花が終わったあとも、葉は光を受けて養分をつくります。',q:'チューリップが養分をたくわえるものは？',choices:['花びらだけ','地下の球根','空中のつる'],answer:1},
{id:'mint',name:'ミント',family:'シソ科',season:'夏〜秋',fact:'葉に香りがあり、向かい合って葉がつくものが多いハーブです。',detail:'ミントにはスペアミントやペパーミントなど、多くの種類があります。地下茎で広がるため、鉢で育てる方法もあります。',q:'ミントでよく知られている特徴は？',choices:['葉に香りがある','海の中で育つ','葉がまったくない'],answer:0},
{id:'morningglory',name:'アサガオ',family:'ヒルガオ科',season:'夏',fact:'つるが伸び、じょうごのような形の花が咲きます。',detail:'支柱などに、つるを巻きつけて育ちます。日本で親しまれるアサガオは、朝に花が開くことが多い植物です。',q:'アサガオは、どうやって支柱を登る？',choices:['根で空を飛ぶ','つるを巻きつける','花びらでつかむ'],answer:1}
];
const KEY='secret-botanical-garden-v1';
const initial=()=>({version:1,seeds:50,owned:{strawberry:1},observed:[],learned:[],selected:'strawberry',draws:0});
function valid(s){return s&&s.version===1&&Number.isSafeInteger(s.seeds)&&s.seeds>=0&&s.seeds<1e9&&Number.isSafeInteger(s.draws)&&s.draws>=0&&s.owned&&typeof s.owned==='object'&&!Array.isArray(s.owned)&&Object.entries(s.owned).every(([k,v])=>PLANTS.some(p=>p.id===k)&&Number.isSafeInteger(v)&&v>0&&v<1e6)&&Object.keys(s.owned).length>0&&['observed','learned'].every(k=>Array.isArray(s[k])&&s[k].every(id=>PLANTS.some(p=>p.id===id)))&&PLANTS.some(p=>p.id===s.selected)&&s.owned[s.selected];}
let state=initial(), storageOK=true;
try{const raw=localStorage.getItem(KEY);if(raw){const parsed=JSON.parse(raw);if(valid(parsed))state=parsed;else storageOK=false;}}catch{storageOK=false;}
let tab='garden',quizIndex=0,answered=false,toastTimer;
const main=document.getElementById('main'),modal=document.getElementById('modal');
function persist(next){try{localStorage.setItem(KEY,JSON.stringify(next));state=next;storageOK=true;document.getElementById('save').textContent='保存済み';return true;}catch{storageOK=false;document.getElementById('save').textContent='保存できません';toast('保存できません。バックアップで進み具合を残せます。');return false;}}
function transact(fn){const next=structuredClone(state);fn(next);return persist(next);}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),3500);}
function art(p){const i=PLANTS.indexOf(p);return `<div class="plant-art" role="img" aria-label="${p.name}のイラスト" style="background-position:${i%3*50}% ${Math.floor(i/3)*100}%"></div>`;}
function cards(ownedOnly=false){return PLANTS.filter(p=>!ownedOnly||state.owned[p.id]).map(p=>`<button class="plant-card ${state.owned[p.id]?'':'locked'}" data-plant="${p.id}">${art(p)}<span class="badge">${state.owned[p.id]?'育成中':'未発見'}</span><strong>${p.name}</strong><small>${p.family} · ${p.season}</small></button>`).join('');}
function render(){document.getElementById('seeds').textContent=state.seeds;document.getElementById('save').textContent=storageOK?'保存済み':'保存できません';document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});
if(tab==='garden'){const p=PLANTS.find(p=>p.id===state.selected);main.innerHTML=`<section class="scene" aria-label="陽が差すひみつの温室"><img src="assets/garden.png" alt="植物が茂る美しい温室"/><span class="scene-label">☀ ひみつの温室</span><span class="scene-note">${Object.keys(state.owned).length}種類の植物が仲間入り</span></section><div class="content garden-content"><section class="today">${art(p)}<div><span class="kicker">今日の観察</span><h2>${p.name}</h2><p>${p.fact}</p><button class="primary" data-observe="${p.id}">観察する</button></div></section><div><button class="gacha" id="draw"><span class="seed-icon">🌰</span><span><strong>たねガチャ</strong><small>集めた種で、植物と出会おう</small></span><span>たね × 50</span></button><p class="muted">初めての観察で20個、クイズで30個。復習クイズでも5個ずつ貯まります。同じ植物は、種15個に変わります。</p></div><section class="collection"><div class="section-title"><h2>わたしの植物園</h2><span class="count">${Object.keys(state.owned).length} / 6 種類</span></div><div class="grid">${cards(true)}</div></section></div>`;}
if(tab==='book')main.innerHTML=`<div class="content"><div class="intro"><span class="kicker">BOTANICAL NOTEBOOK</span><h2>植物の図鑑</h2><p>葉のかたち、花のひみつ。気になる植物を開いてみよう。<br>まだ出会っていない植物も、観察できます。</p><progress max="6" value="${state.observed.length}" aria-label="観察した植物の数"></progress><p class="muted">観察 ${state.observed.length}/6 · クイズ ${state.learned.length}/6</p></div><div class="grid">${cards()}</div><div class="sources"><p>イラストは学習を楽しむための描画です。品種による違いがあります。</p><a href="https://www.shuminoengei.jp/m-pc/a-page_p_top" target="_blank" rel="noopener">もっと調べる：NHK みんなの趣味の園芸 植物図鑑</a></div></div>`;
if(tab==='quiz')renderQuiz();bind();}
function bind(){main.querySelectorAll('[data-plant]').forEach(b=>b.onclick=()=>observe(b.dataset.plant));main.querySelectorAll('[data-observe]').forEach(b=>b.onclick=()=>observe(b.dataset.observe));const draw=document.getElementById('draw');if(draw){draw.disabled=state.seeds<50;draw.onclick=gacha;}}
function show(html){document.getElementById('modal-content').innerHTML=html;if(!modal.open)modal.showModal();}
function observe(id){const p=PLANTS.find(p=>p.id===id),done=state.observed.includes(id);show(`${art(p)}<span class="kicker">${p.family} · ${p.season}</span><h2>${p.name}</h2><p>${p.fact}</p><p>${p.detail}</p><button class="primary" id="learn" ${done?'disabled':''}>${done?'観察ずみ':'観察を記録する · たね +20'}</button>${state.owned[id]?'<div class="actions"><button class="secondary" id="select">温室に飾る</button></div>':''}<p class="muted">知らない植物を口に入れたり、さわったりしないでね。</p>`);document.getElementById('learn').onclick=()=>{if(state.observed.includes(id))return;if(transact(s=>{s.observed.push(id);s.seeds+=20;})){render();observe(id);toast('観察を記録しました。たね +20');}};const select=document.getElementById('select');if(select)select.onclick=()=>{if(transact(s=>s.selected=id)){tab='garden';render();modal.close();toast(`${p.name}を温室に飾りました`);}};}
function pickPlant(){const bytes=new Uint32Array(1);let v;do{crypto.getRandomValues(bytes);v=bytes[0];}while(v>=4294967292);return PLANTS[v%6];}
function gacha(){if(state.seeds<50)return;const p=pickPlant(),duplicate=!!state.owned[p.id];if(!transact(s=>{s.seeds-=50;s.draws++;if(duplicate)s.seeds+=15;else{s.owned[p.id]=1;s.selected=p.id;}}))return;render();show(`<div class="result"><span class="kicker">${duplicate?'また会えたね':'新しい植物を発見！'}</span>${art(p)}<h2>${p.name}</h2><p>${p.fact}</p><p>${duplicate?'持っている植物なので、たね15個になりました。':'あなたの植物園に仲間入りしました。'}</p><button class="primary" id="result-observe">観察する</button><p class="muted">全6種類・それぞれ同じ確率（1/6）</p></div>`);document.getElementById('result-observe').onclick=()=>observe(p.id);}
function renderQuiz(){const p=PLANTS[quizIndex];main.innerHTML=`<div class="content"><div class="intro"><span class="kicker">小さな発見を、おぼえよう</span><h2>植物のクイズ</h2><p>間違えても大丈夫。解説を読んで学ぼう。</p></div><section class="quiz-panel"><span class="kicker">${quizIndex+1} / 6 · ${p.name}</span>${art(p)}<h3>${p.q}</h3><div class="options">${p.choices.map((c,i)=>`<button data-answer="${i}">${c}</button>`).join('')}</div><div id="feedback" class="feedback" role="status"></div></section></div>`;answered=false;main.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(Number(b.dataset.answer)));}
function answer(i){if(answered)return;answered=true;const p=PLANTS[quizIndex];main.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;const v=Number(b.dataset.answer);if(v===p.answer)b.classList.add('correct');else if(v===i)b.classList.add('wrong');});const done=state.learned.includes(p.id);document.getElementById('feedback').innerHTML=`<strong>${i===p.answer?'正解！':'おしい！ 正解は「'+p.choices[p.answer]+'」'}</strong><p>${p.detail}</p><button class="primary" id="claim">${done?'復習を記録する · たね +5':'解説を読んだ · たね +30'}</button>`;document.getElementById('claim').onclick=()=>{const review=state.learned.includes(p.id);if(!transact(s=>{if(!review)s.learned.push(p.id);s.seeds+=review?5:30;}))return;toast(review?'復習しました。たね +5':'学びを記録しました。たね +30');quizIndex=(quizIndex+1)%PLANTS.length;render();};}
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render();window.scrollTo({top:0,behavior:'smooth'});});document.getElementById('close').onclick=()=>modal.close();modal.addEventListener('click',e=>{if(e.target===modal){const r=modal.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)modal.close();}});
document.getElementById('settings').onclick=()=>{show(`<h2>セーブとバックアップ</h2><p>進み具合は、このブラウザに自動保存されます。ガチャの結果は、表示される前に保存します。</p><p class="muted">ブラウザのデータを消すとセーブも消えます。別の端末や公開後のURLへ移すときは、バックアップを使ってください。</p><div class="actions"><button class="primary" id="export">バックアップを保存</button><button class="secondary" id="restore">バックアップを読み込む</button></div>`);document.getElementById('export').onclick=()=>{const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='secret-garden-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};document.getElementById('restore').onclick=()=>document.getElementById('import').click();};
document.getElementById('import').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>100000)throw Error();const parsed=JSON.parse(await file.text());if(!valid(parsed))throw Error();show(`<h2>バックアップを読み込む？</h2><p>現在の進み具合を、たね${parsed.seeds}個・植物${Object.keys(parsed.owned).length}種類のセーブに置き換えます。</p><button class="primary" id="confirm-import">このセーブを読み込む</button>`);document.getElementById('confirm-import').onclick=()=>{if(persist(parsed)){render();modal.close();toast('バックアップを読み込みました');}};}catch{toast('このファイルは読み込めません。セーブは変更していません。');}e.target.value='';};
render();if(!storageOK)toast('セーブを確認できませんでした。バックアップをご確認ください。');
